### ISSUE TITLE
Add and install desktop file

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#101]
This needs to be put in the right location for the system to pick it up and make gooey appear in the desktop menus.

Best docs I found so far are https://stackoverflow.com/questions/25284879/install-desktop-file-with-setup-py

but they refer to an outdated approach. The new one is https://setuptools.pypa.io/en/latest/userguide/datafiles.html

**Comment by mih** [comment]
Here is a draft of the desktop file to deploy

```ini
[Desktop Entry]
Type=Application
Name=DataLad Gooey
GenericName=Data management system
Comment=Manage and work with DataLad datasets
Comment[de]=Nutzen und verwalten von DataLad Datasets
Exec=datalad gooey %f
Terminal=false
Icon=datalad-gooey
Categories=Network;Development;Science
Keywords=rdm;git-annex;git
```

**Comment by mslw** [comment]
So if I understand correctly:
- `setup.py` file is the place where we would move the desktop file to a target location (most likely `~/.local/share/applications`)
- desktop file is linux-specific, and the setup file would need to have a section "if on linux then do this"
- we need to use the approach described in the second link to bundle the desktop file, and then handle file placement in `setup.py`

?

**Comment by mslw** [comment]
I've read some more, and started wondering whether adding a desktop file through the setup script (i.e. on pip install) is against the current good practice.

The setuptools user guide (second link) says at the beginning:
> However, the most common use case for data files distributed with a package is for use *by* the package, usually by including the data files inside the package directory.

And at the end there's a tip:
> If your Python package needs to write to a file for shared data or configuration, you can use standard platform/OS-specific system directories, such as ~/.local/config/$appname or /usr/share/$appname/$version (Linux specific) (footnote: These locations can be discovered with the help of third-party libraries such as[platformdirs). A common approach is to add a read-only template file to the package directory that is then copied to the correct system directory if no pre-existing file is found.

But nothing in the above suggests that this is meant to happen on installation - it only says that a template file can be included in the package directory. Docs above the tip say that the content of such file can be obtained with `files('mypkg.data').joinpath('data1.txt').read_text()` whenever it's needed.

I've also stumbled upon this lengthy discussion: https://discuss.python.org/t/should-there-be-a-new-standard-for-installing-arbitrary-data-files/7853/7. I got a feeling that installing `.desktop` files is not an intended use case for `setup.py` files, and should rather be left to system package installers, best expressed in [this comment](https://discuss.python.org/t/should-there-be-a-new-standard-for-installing-arbitrary-data-files/7853/9):
> Agreed. If you want to install files in machine-wide locations, you should be using an OS-level installer (which is designed to manage for this use case) not a Python-specific one. (...)

and [this comment](https://discuss.python.org/t/should-there-be-a-new-standard-for-installing-arbitrary-data-files/7853/60):
>  .desktop files. You said yourself they are platform specific and only useful if installed into system locations, i.e. not under sys.prefix. So the solutions we’re looking at won’t work for these.

Does this mean we should just bundle the desktop file and leave its installation to system package builders, or do it on first launch / from a menu option after launch, or require users to do it by hand ([e.g.](https://wiki.archlinux.org/title/desktop_entries#Installation) with `desktop-file-install`)?

**Comment by mslw** [comment]
Idea:
- Include the desktop file with the package
- Add a method like `datalad gooey setup`, to be called by the user, which would install the desktop file after the package installation

If `pip install` is the default way of distribution, it would require running two commands instead of one (however, this won't introduce any other operations like changing paths, so the barrier of entry isn't noticeably higher). If we target `apt install` (are we?), then moving the file should be done as part of apt installation.

**Comment by mih** [comment]
> If you want to install files in machine-wide locations, you should be using an OS-level installer (which is designed to manage for this use case) not a Python-specific one.

Yeah, but that is not an adequate description. We want to support `pip install --user`. This is not machine-wide, and not a task for system packager.

Here is what I will/would try.

We can override what the `install` command in setuptools does by passing a new command implementation to `setup(cmdclass=)` or in `setup.cfg` speak

```ini
# setup.cfg
...
[options.entry_points]
distutils.commands =
     foo = mypackage.some_module:foo
```

(from https://setuptools.pypa.io/en/latest/userguide/extension.html#customizing-commands)

We can derive a new command from either of the following two:

- https://github.com/pypa/setuptools/blob/main/setuptools/command/install.py
- https://github.com/pypa/setuptools/blob/main/setuptools/command/install_scripts.py

Our implementation would override the `run()` method, and simply call the original setuptools implementation. At the end however, we check if we are on Linux and if `self.install_dir` looks like we are installing into `~/.local` -- and if we do, we drop the desktop file.

**Comment by mih** [comment]
Yeah, a quick and dirty

```diff
diff --git a/setup.cfg b/setup.cfg
index ca7b0cf..2d32032 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -43,6 +43,8 @@ datalad.extensions =
 # install the GUI starter as a direct entrypoint to avoid the datalad CLI
 # overhead
 gui_scripts = datalad-gooey = datalad_gooey.app:main
+distutils.commands =
+    install_scripts = datalad_gooey.install_helper:install_scripts
 
 [versioneer]
 # See the docstring in versioneer.py for instructions. Note that you must
```

does not work, because 

```py
      Traceback (most recent call last):
        File "/home/mih/env/datalad-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/mih/env/datalad-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/mih/env/datalad-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 311, in run
          install_scripts = self.reinitialize_command('install_scripts')
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 200, in reinitialize_command
          cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 312, in reinitialize_command
          return self.distribution.reinitialize_command(command, reinit_subcommands)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 945, in reinitialize_command
          command = self.get_command_obj(command_name)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 864, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-vbkw2xlk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 954, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/home/mih/hacking/datalad/gooey/datalad_gooey/__init__.py", line 22, in <module>
          from datalad.support.extensions import register_config
        File "/home/mih/hacking/datalad/git/datalad/__init__.py", line 108, in <module>
          from .config import ConfigManager
        File "/home/mih/hacking/datalad/git/datalad/config.py", line 19, in <module>
          from fasteners import InterProcessLock
      ModuleNotFoundError: No module named 'fasteners'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for datalad-gooey
```

It seems to reinvent itself in some kind of barebone environement.

This is not the way to go.

**Comment by mih** [comment]
`datalad gooey --postinstall` is now provided for users to deploy a desktop file.
