### ISSUE TITLE
Very long errors - maybe initimidating?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#141]
I accidentally supplied a wrong source path in a clone command, and the error was longer than the console window was big:

```
install(error): /tmp/mynewdataset (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /home/adina/data/human-connectome-project-openaccess
  CommandError: 'git -c diff.ignoreSubmodules=none clone --progress /home/adina/data/human-connectome-project-openaccess /tmp/mynewdataset' failed with exitcode 128 [err: 'fatal: repository '/home/adina/data/human-connectome-project-openaccess' does not exist']]
Traceback (most recent call last): File "/home/adina/repos/datalad-gooey/datalad_gooey/dataladcmd_exec.py", line 138, in _cmdexec_thread for res in cmd(**cmdkwargs): File "/home/adina/env/gooey/lib/python3.9/site-packages/datalad/interface/utils.py", line 424, in generator_func raise IncompleteResultsError( datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed: [{'action': 'install', 'message': ('Failed to clone from any candidate source URL. Encountered ' 'errors per each url were:\n' '- %s', '/home/adina/data/human-connectome-project-openaccess\n' " CommandError: 'git -c diff.ignoreSubmodules=none clone " '--progress /home/adina/data/human-connectome-project-openaccess ' "/tmp/mynewdataset' failed with exitcode 128 [err: 'fatal: " 'repository ' "'/home/adina/data/human-connectome-project-openaccess' does not " "exist']"), 'path': '/tmp/mynewdataset', 'source': {'default_destpath': 'human-connectome-project-openaccess', 'giturl': '/home/adina/data/human-connectome-project-openaccess', 'source': '/home/adina/data/human-connectome-project-openaccess', 'type': 'giturl', 'version': None}, 'source_url': '/home/adina/data/human-connectome-project-openaccess', 'status': 'error', 'type': 'dataset'}] 
```

![Screenshot from 2022-09-19 12-09-23](https://user-images.githubusercontent.com/29738718/190995514-1a13fa42-76b7-4db1-8a29-88bc08e39fc0.png)

I wonder if it would be easy to wrap the Traceback in expandable details HTML tags...

**Comment by adswa** [comment]
I read a bit, and the ``QPlainTextEdit``, kept simple for speed, does not support the ``<details></details>`` HTML tag. Sadly, the more sophisticated ``QTextEdit`` doesn't either. While neither throws an error, the Captured Exceptions Traceback just isn't enclosed in a toggleable details section if I enclose it like this:

```diff
@@ -145,8 +146,9 @@ class GooeyApp(QObject):
             self.get_widget('statusbar').showMessage(f'`{cmdname}` failed')
             # but also barf the error into the logviewer
             lv = self.get_widget('logViewer')
-            lv.appendHtml(
-                f'<font color="red">{ce.format_standard()}</font>'
+            lv.insertHtml(
+                f'<details style="color:red">{ce.format_standard()}</details>'
             )

```

**Comment by adswa** [comment]
How about we create a dedicated 'Traceback' Tab next to the 'Log/Console' Tab and send Tracebacks to this Tab?

**Comment by mih** [comment]
#152 is merged.
