### ISSUE TITLE
Procedure discovery error during dataset creation

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-gooey#185]
When creating a new dataset through Dataset -> Create a dataset, with `cfg_text2git` added to Configuration procedure(s), I get the following in the command log:
```
Running: create(path='/home/mszczepanik/Documents/foo', cfg_proc=['cfg_text2git']) failed! (see error log for details)
```
And the error log:
```
Running: create(path='/home/mszczepanik/Documents/foo', cfg_proc=['cfg_text2git']) failed!
Traceback (most recent call last):
  File "/home/mszczepanik/Documents/datalad-gooey/datalad_gooey/dataladcmd_exec.py", line 156, in _cmdexec_thread
    for res in cmd(**cmdkwargs):
  File "/home/mszczepanik/.virtualenvs/dl-gooey-dev/lib/python3.9/site-packages/datalad/interface/utils.py", line 357, in generator_func
    for r in _process_results(
  File "/home/mszczepanik/.virtualenvs/dl-gooey-dev/lib/python3.9/site-packages/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/home/mszczepanik/.virtualenvs/dl-gooey-dev/lib/python3.9/site-packages/datalad/core/local/create.py", line 360, in __call__
    raise ValueError("Cannot find procedure with name "
ValueError: Cannot find procedure with name 'cfg_text2git'
```

I suppose this is related to whether the procedure names are given with or without the "cfg_" prefix to the underlying function call.

**Comment by mih** [comment]
:facepalm: Thx!
