### ISSUE TITLE
Consider switching the internal pointers in the FSModel to DataLadTreeNode objects

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#22]
Right now it points to their `.path` properties. This makes little sense from my current POV. Maybe sorting has made me make this choice, but I somehow doubt it.

It feels like using node objects would also remove the need for node lookup by path via `DataladTree.__getitem__()`

**Comment by mih** [comment]
Observation that may call for yet another approach:

```
...
[Level 9] _inspect_changed_dir() -> updated node children 
[Level 9] GooeyFilesystemBrowser._inspect_changed_dir(PosixPath('/tmp/ebrains')) 
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/gooey/datalad_gooey/fsview_model.py", line 267, in parent
    pnode = self._tree[child_path.parent]
  File "/usr/lib/python3.10/pathlib.py", line 868, in parent
    drv = self._drv
AttributeError: 'PosixPath' object has no attribute '_drv'
```

The first FSWatcher triggered run had child nodes garbage collected and replaced. Something in the code still held onto pointers to their path objects.

**Comment by mih** [comment]
This is done. Push is pending.
