### ISSUE TITLE
Crashes during `lsdir`

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-gooey#230]
I currently get quite a lot of those:

```
EXECINTHREAD gooey_lsdir {'path': PosixPath('/tmp/another'), 'result_renderer': 'disabled', 'on_failure': 'ignore', 'return_type': 'generator'} {'preferred_result_interval': 0.2, 'result_override': {'gooey_parent_item': <datalad_gooey.fsbrowser_item.FSBrowserItem object at 0x7f8fa651ab80>, 'gooey_no_existing_item': False}}
Traceback (most recent call last):
  File "/home/ben/work/hacking/datalad-gooey/datalad_gooey/fsbrowser.py", line 354, in _inspect_changed_dir
    self._inspect_changed_dir(pathobj.parent.parent.parent)
  File "/home/ben/work/hacking/datalad-gooey/datalad_gooey/fsbrowser.py", line 375, in _inspect_changed_dir
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "/home/ben/work/hacking/datalad-gooey/datalad_gooey/fsbrowser.py", line 371, in _inspect_changed_dir
    parent = item.parent()
RuntimeError: Internal C++ object (FSBrowserItem) already deleted.
```

In this particular case it's after a `drop` of `/tmp/another`. However, I got a bunch of those:

```
Traceback (most recent call last):
  File "/home/ben/work/hacking/datalad-gooey/datalad_gooey/fsbrowser.py", line 371, in _inspect_changed_dir
    parent = item.parent()
RuntimeError: Internal C++ object (FSBrowserItem) already deleted.
```

before where the path given to lsdir was not deleted.

**Comment by mih** [comment]
Closing for now
