### ISSUE TITLE
Getting subdatasets might have suboptimal UX

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#238]
Consider cloning github.com/psychoinformatics-de/studyforrest-data (a dataset with many subdatasets). If one wants to get a subdataset,, right-clicking the subdataset in question, selecting get from the context menu, and clicking ok will fail with "no installed dataset found"

```
Running: Dataset('/home/adina/studyforrest-data/original/3T_multiresolution_fmri').get(get_data=False) failed!
Traceback (most recent call last):
  File "/home/adina/repos/datalad-gooey/datalad_gooey/dataladcmd_exec.py", line 159, in _cmdexec_thread
    for res in cmd(**cmdkwargs):
  File "/home/adina/env/gooey/lib/python3.10/site-packages/datalad/interface/utils.py", line 357, in generator_func
    for r in _process_results(
  File "/home/adina/env/gooey/lib/python3.10/site-packages/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/home/adina/env/gooey/lib/python3.10/site-packages/datalad/distribution/get.py", line 857, in __call__
    refds = require_dataset(
  File "/home/adina/env/gooey/lib/python3.10/site-packages/datalad/distribution/dataset.py", line 595, in require_dataset
    raise NoDatasetFound(
datalad.support.exceptions.NoDatasetFound: No installed dataset found at /home/adina/studyforrest-data/original/3T_multiresolution_fmri
```

The dataset get is parametrized with is the uninstalled subdataset. But in order for the command to work, the dataset parameter would need to be the superdataset. 

No good idea how to fix this other with documentation about it

**Comment by adswa** [comment]
Happened in  #244
