### ISSUE TITLE
ValueError: s not in the subpath of '' 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-gooey#281]
```shell
(git)lena:~datalad/datalad-gooey[main]git
$> datalad gooey -p .
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute and QSGRendererInterface::OpenGLRhi using QQuickWindow::setGraphicsApi before constructing QGuiApplication.
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-gooey/datalad_gooey/fsbrowser.py", line 276, in _process_item_annotation_queue
    paths_to_investigate = [
  File "/home/yoh/proj/datalad/datalad-gooey/datalad_gooey/fsbrowser.py", line 277, in <listcomp>
    c.pathobj.relative_to(dsroot)
  File "/usr/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/home/yoh/proj/datalad/datalad-gooey/.all-contributorsrc' is not in the subpath of '' OR one path is relative and the other is absolute.
gooey(ok): .
```

happens if I start gooey and expand the tree one level and wait

**Comment by mih** [comment]
I can reproduce, and will fix.
