### ISSUE TITLE
Saving a file in a dataset (with gooey) does not trigger reannotation

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#338]
The file remains untracked, until a manual refresh

**Comment by mih** [comment]
On first attempt, this behavior does not replicate (in the very same dataset).

**Comment by jsheunis** [comment]
I tried this now on my mac using current `main`, and I can't replicate, but I do get a different error:

- Create file inside dataset (outside of gooey)
- File shows up in gooey file tree as untracked
- In gooey, right click > File commands > Save the state in a dataset
- Add a commit message and press ok:

```

status(error): ../Data/ccc/testy.txt [path not underneath the reference dataset /Users/jsheunis/Documents/psyinf/datalad-gooey-jsh]
action summary:
  save (notneeded: 1)
  status (error: 1)
Traceback (most recent call last): File "/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh/datalad_gooey/dataladcmd_exec.py", line 138, in _cmdexec_thread for res in cmd(**cmdkwargs): File "/Users/jsheunis/opt/miniconda3/envs/meow2/lib/python3.9/site-packages/datalad/interface/utils.py", line 424, in generator_func raise IncompleteResultsError( datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed: [{'action': 'status', 'message': ('path not underneath the reference dataset %s', '/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh'), 'path': '/Users/jsheunis/Documents/psyinf/Data/ccc/testy.txt', 'refds': '/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh', 'status': 'error'}] 
```

I'm not sure why it sees `/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh` as a reference dataset? I started the gooey from that location, but with this command:

```
datalad gooey -p ~/Documents/psyinf/Data/
```

**Comment by mih** [comment]
@jsheunis please file that as a separate issue.

**Comment by jsheunis** [comment]
👍 https://github.com/datalad/datalad-gooey/issues/347
