### ISSUE TITLE
Error when saving state in dataset after adding file

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#347]
I tried replicating https://github.com/datalad/datalad-gooey/issues/338 now on my mac using current `main`, and I can't replicate, but I do get a different error:

- Create file inside dataset (outside of gooey)
- File shows up in gooey file tree as untracked
- In gooey, right click > File commands > Save the state in a dataset
- Add a commit message and press ok:

```

status(error): ../Data/ccc/testy.txt [path not underneath the reference dataset /Users/jsheunis/Documents/psyinf/datalad-gooey-jsh]
action summary:
  save (notneeded: 1)
  status (error: 1)
Traceback (most recent call last): File "/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh/datalad_gooey/dataladcmd_exec.py", line 138, in _cmdexec_thread for res in cmd(**cmdkwargs): File "/Users/jsheunis/opt/miniconda3/envs/meow2/lib/python3.9/site-packages/datalad/interface/utils.py", line 424, in generator_func raise IncompleteResultsError( datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed: [{'action': 'status', 'message': ('path not underneath the reference dataset %s', '/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh'), 'path': '/Users/jsheunis/Documents/psyinf/Data/ccc/testy.txt', 'refds': '/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh', 'status': 'error'}] 
```

I'm not sure why it sees `/Users/jsheunis/Documents/psyinf/datalad-gooey-jsh` as a reference dataset? I started the gooey from that location, but with this command:

```
datalad gooey -p ~/Documents/psyinf/Data/
```

_Originally posted by @jsheunis in https://github.com/datalad/datalad-gooey/issues/338#issuecomment-1278596468_

**Comment by jsheunis** [comment]
I think I installed the wrong, much older, version of the app. All good now. No problem anymore.
