### ISSUE TITLE
Ability to kill

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-gooey#38]
Relates to #31 probably since would need to kill first those commands.  ATM seems can't kill the gooey process as well because some underlying datalad call is still holding it or smth like that

```
$> datalad gooey --path ~/datalad
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute and QSGRendererInterface::OpenGLRhi using QQuickWindow::setGraphicsApi before constructing QGuiApplication.
QUEUEDIR /home/yoh/datalad
ANNOTATE! 1
EXECINTHREAD status {'dataset': '/home/yoh/datalad', 'path': PosixPath('/home/yoh/datalad')}
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
^CTraceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-gooey/datalad_gooey/app.py", line 95, in <lambda>
    lambda i, cmd, args, ce: self.get_widget('statusbar').showMessage(
KeyboardInterrupt
^CTraceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-gooey/datalad_gooey/fsbrowser.py", line 79, in _directory_annotation
    def _directory_annotation(self):
KeyboardInterrupt
^C^C^C^CTraceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-gooey/datalad_gooey/fsbrowser.py", line 79, in _directory_annotation
    def _directory_annotation(self):
KeyboardInterrupt
^C^C^C^C^CTraceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-gooey/datalad_gooey/fsbrowser.py", line 79, in _directory_annotation
    def _directory_annotation(self):
KeyboardInterrupt
...
```

**Comment by mih** [comment]
I looked into this now and will close this issue in favor of #31, as they turn out to be one and the same.
