### ISSUE TITLE
getting file from right-click context menu violates constraints

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#406]
Calling get for a single file from a right-click context menu violates a constraint and prevents successful command parametrization/execution:
[Screencast from 2022-10-27 14-13-46.webm](https://user-images.githubusercontent.com/29738718/198281416-45b9341e-f8e9-45bf-9bf7-42774806b7cc.webm)

The error is:

```
Traceback (most recent call last):
  File "/home/adina/repos/datalad-gooey/datalad_gooey/dataladcmd_ui.py", line 105, in configure
    self._parameters = populate_form_w_params(
  File "/home/adina/repos/datalad-gooey/datalad_gooey/param_form_utils.py", line 139, in populate_form_w_params
    p[1].set_from_spec(cmdkwargs_defaults)
  File "/home/adina/repos/datalad-gooey/datalad_gooey/param.py", line 191, in set_from_spec
    self.set(spec[self.__name])
  File "/home/adina/repos/datalad-gooey/datalad_gooey/param.py", line 163, in set
    val = self.get_constraint()(value) if value != _NoValue else value
  File "/home/adina/repos/datalad/datalad/support/constraints.py", line 437, in __call__
    raise ValueError("all alternative constraints (%s) violated while testing value %r"
ValueError: all alternative constraints ([constraint:<class 'list'>(constraint:path), constraint:None]) violated while testing value PosixPath('/home/adina/ml-books/T.Hastie_R.Tibshirani_J.Friedman-The_Elements_of_Statistical_Learning_Data_Mining_Inference_and_Prediction.pdf')
```

This does not happen when parametrizing ``Get`` from the right-click context menu of the top level dataset.

**Comment by adswa** [comment]
I assume that @mih's work on #401 can more easily fix this/take this issue into account than an isolated effort on the current constraint system.

**Comment by mih** [comment]
Yes, the open PR does that already, I believe

**Comment by adswa** [comment]
I can confirm that issue disappears with #401
