### ISSUE TITLE
Install Start issue: Mac OS 13.6.1 Apple Silicon

### ISSUE THREAD

**Issue by dkp** [datalad/datalad-gooey#438]
### Is it a new bug?

I did not find an existing issue about my problem

### What is the problem?

The gui does not start on mac, despite following the instructions to create the venv and start the program from the command line.  See the detailed error messages in additional context.
____
Given your checklist below, I also tried brew install datalad-gooey, but it does not appear to exist:

Warning: No available formula with the name "datalad-gooey". Did you mean datalad?

### What steps will reproduce the problem?

python3 -m venv ~/.venvs/datalad-gooey
source ~/.venvs/datalad-gooey/bin/activate
pip install datalad_gooey

datalad-gooey
datalad gooey
datalad: Unknown command 'gooey'.  See 'datalad --help'.

datalad_gooey 
zsh: command not found: datalad_gooey

### Additional context

python3 -m venv ~/.venvs/datalad-gooey
source ~/.venvs/datalad-gooey/bin/activate
pip install datalad_gooey

(datalad-gooey) 🍎 dpat@lolo bin % datalad-gooey
Traceback (most recent call last):
  File "/Users/dpat/.venvs/datalad-gooey/bin/datalad-gooey", line 5, in <module>
    from datalad_gooey.app import main
  File "/Users/dpat/.venvs/datalad-gooey/lib/python3.11/site-packages/datalad_gooey/__init__.py", line 25, in <module>
    import datalad_gooey.patches
  File "/Users/dpat/.venvs/datalad-gooey/lib/python3.11/site-packages/datalad_gooey/patches/__init__.py", line 1, in <module>
    from . import (
  File "/Users/dpat/.venvs/datalad-gooey/lib/python3.11/site-packages/datalad_gooey/patches/clone.py", line 8, in <module>
    from datalad_next.patches import clone as mod_clone
ImportError: cannot import name 'clone' from 'datalad_next.patches' (/Users/dpat/.venvs/datalad-gooey/lib/python3.11/site-packages/datalad_next/patches/__init__.py)
(datalad-gooey) 🍎 dpat@lolo bin % datalad gooey
[WARNING] Failed to load entrypoint gooey from datalad.extensions: ImportError(cannot import name 'clone' from 'datalad_next.patches' (/Users/dpat/.venvs/datalad-gooey/lib/python3.11/site-packages/datalad_next/patches/__init__.py))
datalad: Unknown command 'gooey'.  See 'datalad --help'.

### How did you install the App?

- [ ] Via the Windows installer
- [X] Using pip (``pip install datalad-gooey``)
- [X] Using brew (``brew install datalad-gooey``)
- [ ] Using conda (``conda install -c forge datalad-gooey``)
- [ ] Not sure
- [ ] Other

### System information

Mac OS 13.6.1
Apple M2 Max

Using zsh

**Comment by adswa** [comment]
Thanks for the issue, and for including the traceback! The entire experience sounds sub-optimal, but judging from the traceback, the most pressing issue at hand looks like a version incompatibility (an attempted import fails from a recent ``datalad-next``). And looking further, the fix should be trivial - we need to release the current version to [PyPi](https://pypi.org/project/datalad-gooey/). For some reason, we only updated the previous releases as a Windows installer. I'll take a look what else might need doing before that. Ping @mih.

**Comment by adswa** [comment]
Another ping on this - @mih, can we release this? 

Intermediate work-arounds for anyone coming across this issue are to install from source. For example, by git cloning the repository, and running ``pip install .`` inside of it.

**Comment by dkp** [comment]
Your workaround works for me!  Thank you! (Great project)
